### ISSUE TITLE
Can Change Checkpoint be used with animatediff?

### ISSUE THREAD

**Issue by WainWong** [chaosaiart/Chaosaiart-Nodes#1]
Can Change Checkpoint be used with animatediff?

**Comment by chaosaiart** [comment]
It should already work.

Can you specify the exact issue for me? I haven't worked much with AnimteDiff so far. My GPU (VRAM) doesn't support animateDiff ? 
where is the Problem ?

**Comment by WainWong** [comment]
Thanks for the reply, I haven't tried it yet, I just wanted to ask about his compatibility with animatediff, I'll test it out!
